### ISSUE TITLE
DB prefix aanpassen

### ISSUE THREAD

**Issue by maartenvangelder** [grrr-amsterdam/wordpress-scaffold#3]
Het is veiliger om de DB prefix aan te passen. Dit kan de klantnaam of iets randoms zijn. Als het maar niet WP_ is, dit weten de hackers inmiddels ook :).

DB_PREFIX=grrr_ # security

**Comment by HammenWS** [comment]
Added DB_PREFIX as configuration option in the composer post-create-project script, with `grrr` as default.
