### ISSUE TITLE
prepend, append en wrap functie

### ISSUE THREAD

**Issue by maartenvangelder** [grrr-amsterdam/wordpress-scaffold#5]
Handige functies om iets voor, achter of om een waarde te plaatsen. En alleen als er een waarde is.

```
/*
 *   Prepend content if value exists
 *   Usage: prepend(get_something(), ' - ');
 *   Example: 8 juni 2017 - Amsterdam - Grrr HQ
 */
function prepend( $value = '', $prepend) {
    if ( !empty( $value ) ) {
        return $prepend . $value;
    }
}

/*
 *  Append content if value exists
 *  Usage: append(get_something(), '<br>');
 *  Example: 8 juni 2017<br>Amsterdam<br>Grrr HQ<br>
 */
function append( $value = '', $append) {
    if ( !empty( $value ) ) {
        return $value . $append;
    }
}

/*
 *  Wrap content if value exists
 *  Usage: append(get_something(), '<h2>', '</h2>');
 *  Example: <h2>8 juni 2017 - Amsterdam - Grrr HQ</h2>
 */
function wrap( $value = '', $prepend, $append) {
    if ( !empty( $value ) ) {
        return $prepend . $value . $append;
    }
}
```

**Comment by schoenkaft** [comment]
The first two can be replaced by using [Garp Functional](https://github.com/grrr-amsterdam/garp-functional/tree/master/library/Garp/Functional). This way we have even more functional tools available.

The last one is not available in Garp Functional as far as I can tell, although I guess the most common use case would be usage in a template. In that case this would be more explicit/preferred:

```html
<h2><?= get_something() ?></h2>
```

There will probably be use case for `wrap` though. Will check if this is something we could/should add to Garp Functional!

**Comment by harmenjanssen** [comment]
I appreciate the love for Garp Functional ❤️
I don't have a `wrap` function but it could be composed from other bits. Since all arguments are required it's almost a shame to not simply implement it like this:

```php
function wrap(string $prepend, string $value, string $append): string {
  return implode('', func_get_args());
}
```

It's a little weird by the way to have an optional parameter in the first position.  
A lot of code style checking software will complain about that.
